Update testar_selenium.yml

diff --git a/.github/workflows/testar_selenium.yml b/.github/workflows/testar_selenium.yml
--- a/.github/workflows/testar_selenium.yml
+++ b/.github/workflows/testar_selenium.yml
@@ -54,3 +54,29 @@ jobs:
       - name: Verificar portas ativas
         run: |
           netstat -tuln | grep 4444 || (echo "❌ ERRO: A porta 4444 não está ativa!" && cat selenium.log && exit 1)
+
+      - name: Run R script
+        run: |
+          Rscript -e '
+            renv::activate();
+            print(.libPaths());
+            library(httr);
+            print(installed.packages()[,1]);
+            print(Sys.getenv("RENV_PATHS_ROOT"));
+            source("gs/rscript_teste.R")
+          '
+
+      - name: Check if CSV file exists
+        run: |
+          if [ ! -f "gs/SimuladorEletricidade_OF_MN_2025_2.csv" ]; then
+            echo "::error::CSV file does not exist. Skipping commit."
+            exit 1
+          fi
+          echo "CSV file exists. Proceeding to commit."
+
+      - name: Commit new file
+        uses: EndBug/add-and-commit@v9
+        with:
+          add: "gs/SimuladorEletricidade_OF_MN_2025_3.csv"
+          message: "Adiciona novo arquivo gerado pelo workflow"
+          github_token: ${{ secrets.PAT_TOKEN }}
